# Generated by Django 3.2.25 on 2024-08-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='code_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='group_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Detail', models.CharField(max_length=1000)),
                ('photo', models.FileField(upload_to='group_photos/')),
                ('grpName', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.use_table')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sample_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=5000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=100)),
                ('email', models.CharField(max_length=1000)),
                ('photo', models.FileField(upload_to='')),
                ('place', models.CharField(max_length=1000)),
                ('country_code', models.IntegerField(max_length=3)),
                ('phone', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='share_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('CODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.code_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='share_group_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('CODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.code_table')),
                ('GROUP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_table')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('photo', models.FileField(upload_to='group_photos/')),
                ('message', models.CharField(max_length=5000)),
                ('FROM_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
                ('TO_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
    
        migrations.CreateModel(
            name='group_members_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('GROUP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('replay', models.CharField(max_length=1000)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('replay', models.CharField(max_length=1000)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('GROUP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
    ]
