# Generated by Django 6.0 on 2025-12-17 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpName', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('Detail', models.CharField(max_length=1000)),
                ('photo', models.FileField(upload_to='group_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='sample_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=10000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='media/')),
                ('type', models.CharField(default='user', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='share_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Viewed', 'Viewed')], default='Pending', max_length=10)),
                ('FROMUSER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='app.user_table')),
                ('TOUSER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='share_group_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=10000)),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('GROUP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('GROUP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='group_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table'),
        ),
        migrations.CreateModel(
            name='group_members_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('GROUP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('reply', models.CharField(default='pending', max_length=1000)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='code_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Viewed', 'Viewed')], default='Pending', max_length=10)),
                ('FROM_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.user_table')),
                ('TO_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.user_table')),
            ],
        ),
    ]
