# Generated by Django 6.0 on 2025-12-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_table',
            old_name='user',
            new_name='LOGIN',
        ),
    ]
