# Generated by Django 5.1.4 on 2025-03-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_table',
            name='code',
            field=models.CharField(max_length=10000),
        ),
    ]
