# Generated by Django 5.1.4 on 2025-03-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_code_table_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_programs',
            name='code',
            field=models.CharField(max_length=10000),
        ),
    ]
