# Generated by Django 6.0 on 2025-12-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_user_table_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='type',
        ),
    ]
