# Generated by Django 6.0 on 2025-12-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_table_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='type',
            field=models.CharField(default='user', max_length=15),
        ),
    ]
