# Generated by Django 5.1.4 on 2025-03-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sample_programs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_group_table',
            name='code',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='share_table',
            name='code',
            field=models.CharField(max_length=10000),
        ),
    ]
