# Generated by Django 6.0 on 2025-12-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_table_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='name',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
    ]
