# Generated by Django 6.0 on 2025-12-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
