# Generated by Django 6.0 on 2025-12-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_table_address_alter_user_table_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
